format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: android

workflows:
  run_tests:
    description: |
      The workflow executes the tests. The workflow will fail if the tests fail.
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - restore-gradle-cache@1: {}
    - script@1:
        title: Set up local.properties
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            echo "sdk.dir=$ANDROID_HOME" > local.properties
    - script@1:
        title: Make gradlew executable
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            chmod +x ./gradlew
    - script@1:
        title: Test Gradle wrapper
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            export JAVA_TOOL_OPTIONS="-Xmx2048m"
            ./gradlew help
    - android-unit-test@1:
        inputs:
        - project_location: $BITRISE_SOURCE_DIR
        - module: app
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}

  build:
    description: |
      Builds the Android app
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - restore-gradle-cache@1: {}
    - script@1:
        title: Set up local.properties
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            echo "sdk.dir=$ANDROID_HOME" > local.properties
    - script@1:
        title: Make gradlew executable
        inputs:
        - content: |
            #!/usr/bin/env bash
            set -ex
            chmod +x ./gradlew
    - android-build@1:
        inputs:
        - project_location: $BITRISE_SOURCE_DIR
        - module: app
        - variant: debug
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}

app:
  envs:
  - opts:
      is_expand: false
    GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
