workflows:
  android-native-workflow:
    name: Android Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Opcional para Google Play)
      vars:
        PACKAGE_NAME: "com.company.gestion"
        GOOGLE_PLAY_TRACK: internal
      java: 11
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build release APK
        script: |
          ./gradlew assembleRelease
      - name: Build release App Bundle
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - angelb042512@gmail.com
        notify:
          success: true
          failure: true

  android-debug-workflow:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.company.gestion"
      java: 11
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
      - name: Run unit tests
        script: |
          ./gradlew test
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/tests/**/*
    publishing:
      email:
        recipients:
        - angelb042512@gmail.com
        notify:
          success: true
          failure: true
